Replaced eigen+kdl conversions with tf2_eigen + tf2_kdl (#2472)
Replaced eigen_conversions and kdl_conversions with modern tf2 variants: tf2_eigen and tf2_kdl
* Use tf2::toMsg / tf2::fromMsg where possible
* Use tf2::convert when converting between two non-message types
  exception: conversion to/from KDL types:
  Due to a bad implementation of tf2_kdl (not using templates), tf2::convert cannot be used.