MSA: Fix templates (#2695)
* Add missing arg `execution_type` to avoid the error:
  RLException: unused args [execution_type] for include of [ [...]moveit_controller_manager.launch.xml]
* Fix package path for Pilz pipeline