Fix missing include
Compile fails on Windows:
C:\PROGRA~2\MICROS~1\2019\ENTERP~1\VC\Tools\MSVC\1416~1.270\bin\HostX64\x64\cl.exe  /nologo /TP -DBOOST_ALL_NO_LIB -DBOOST_CHRONO_DYN_LINK -DBOOST_DATE_TIME_DYN_LINK -DBOOST_FILESYSTEM_DYN_LINK -DBOOST_PROGRAM_OPTIONS_DYN_LINK -DBOOST_SYSTEM_DYN_LINK -DBOOST_THREAD_DYN_LINK -DNOMINMAX -DROSCONSOLE_BACKEND_LOG4CXX -DROS_BUILD_SHARED_LIBS=1 -DROS_PACKAGE_NAME=\"moveit_ros_move_group\" -DWIN32_LEAN_AND_MEAN -D_USE_MATH_DEFINES -Dmoveit_move_group_capabilities_base_EXPORTS -I%SRC_DIR%\ros-noetic-moveit-ros-move-group\src\work\include -I%PREFIX%\Library\include -I%PREFIX%\Library\include\eigen3 -I%PREFIX%\Library\cmake\..\include -I%PREFIX%\Library\CMake\..\include -I%PREFIX%\Library\share\xmlrpcpp\cmake\..\..\..\include\xmlrpcpp /DWIN32 /D_WINDOWS /W3 /GR /EHsc /MD /O2 /Ob2 /DNDEBUG   /D _VARIADIC_MAX=10 /Zc:__cplusplus /showIncludes /FoCMakeFiles\moveit_move_group_capabilities_base.dir\src\move_group_context.cpp.obj /FdCMakeFiles\moveit_move_group_capabilities_base.dir\ /FS -c %SRC_DIR%\ros-noetic-moveit-ros-move-group\src\work\src\move_group_context.cpp
%SRC_DIR%\ros-noetic-moveit-ros-move-group\src\work\include\moveit/move_group/move_group_context.h(73): error C2039: 'string': is not a member of 'std'