setup_assistant: Add missing execution_type arg
This is necessary to avoid the following error:

RLException: unused args [execution_type] for include of [ [...]moveit_controller_manager.launch.xml]