Unify usage of tf2::toMsg, tf2::fromMsg, and tf2::convert
* Use tf2::toMsg / tf2::fromMsg where possible
* Use tf2::convert when converting between two non-message types
  exception: conversion to/from KDL types:
             Due to a bad implementation of tf2_kdl (not using templates), tf2::convert cannot be used.