drop implicit CC definition
To avoid the following warning in clang 14.0.6.
Whether the warning is broken in the case where the user declares the
*default* implementation can be seen as an open debate.

In file included from moveit/moveit_core/collision_detection/include/moveit/collision_detection/collision_env.h:39:
moveit/moveit_core/collision_detection/include/moveit/collision_detection/collision_matrix.h:98:3: error: definition of implicit
copy assignment operator for 'AllowedCollisionMatrix' is deprecated because it has a user-declared copy constructor [-Werror,-Wdeprecated-copy]
  AllowedCollisionMatrix(const AllowedCollisionMatrix& acm) = default;
  ^
moveit/moveit_core/planning_scene/src/planning_scene.cpp:429:48: note: in implicit copy assignment operator for 'collision_detection::AllowedCollisionMatrix' first required here
    scene->getAllowedCollisionMatrixNonConst() = *acm_;